export const services =  {
    categories: ['All', 'Massage', 'Water', 'Ammenities'],
    packages: [
        { id: 1, image: '/assets/img/Services/service-1.jpg', title: 'Sauna', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 2, image: '/assets/img/Services/service-2.jpg', title: 'Swimming Lanes', category: 'Water', description: 'A description of our service...', cost: 15000 },
        { id: 3, image: '/assets/img/Services/service-3.jpg', title: 'Room for 2', category: 'Water', description: 'A description of our service...', cost: 5000 },
        { id: 4, image: '/assets/img/Services/service-4.jpg', title: 'Swedish Massage', category: 'Massage', description: 'A description of our service...', cost: 8000 },
        { id: 5, image: '/assets/img/Services/service-5.jpg', title: 'Single Serving Tub', category: 'Water', description: 'A description of our service...', cost: 7500 },
        { id: 6, image: '/assets/img/Services/service-6.jpg', title: 'Facial ', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 7, image: '/assets/img/Services/service-7.jpg', title: 'Open Swim', category: 'Water', description: 'A description of our service...', cost: 8000 },
        { id: 8, image: '/assets/img/Services/service-8.jpg', title: 'Candlelight Massage', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 9, image: '/assets/img/Services/service-9.jpg', title: 'Couples Day', category: 'Water', description: 'A description of our service...', cost: 7000 },
        { id: 10, image: '/assets/img/Services/service-10.jpg', title: 'Pedicure', category: 'Ammenities', description: 'A description of our service...', cost: 4000 },
        { id: 11, image: '/assets/img/Services/service-11.jpg', title: 'Girls Day', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 12, image: '/assets/img/Services/service-12.jpg', title: 'Group Gathering', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 13, image: '/assets/img/Services/service-13.jpg', title: 'Cold and Hot Treament', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 14, image: '/assets/img/Services/service-14.jpg', title: 'Service 14', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 15, image: '/assets/img/Services/service-15.jpg', title: 'Full Body Scrub', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 16, image: '/assets/img/Services/service-16.jpg', title: 'Deep tissue', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 17, image: '/assets/img/Services/service-17.jpg', title: 'Hot Stone Massage', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 18, image: '/assets/img/Services/service-18.jpg', title: 'Hot, Cold and In Between', category: 'Water', description: 'A description of our service...', cost: 3500 },
        { id: 19, image: '/assets/img/Services/service-19.jpg', title: 'Me Time', category: 'Water', description: 'A description of our service...', cost: 9000 },
        { id: 20, image: '/assets/img/Services/service-20.jpg', title: 'Reflexology', category: 'Ammenities', description: 'A description of our service...', cost: 2000 },
    ],
}